#!/usr/bin/env python3
"""build_project_state.py — generate PROJECT-STATE.md from the live repo.

HANDOFF-consolidation JOB 8. The prior PROJECT-STATE lived off-repo in Project
knowledge, drifted five weeks, and produced three wrong answers in one session
(it misreported languages 6-vs-12, lieux 392-vs-434, pages ~2 350-vs-6 026).
A hand-authored state doc IS the §2 drift anti-pattern. This derives every
number from `data/languages.json`, `Json/*.json`, the built tree, the registries
and `scripts/gate_*.py` — so PROJECT-STATE.md cannot drift: it is regenerated by
build_all on every run and its numbers are always what the repo actually is.

Writes PROJECT-STATE.md at repo root. Deterministic (same commit → same file;
the HEAD sha is stable within a build, so the byte-stable double build passes).
"""
import glob
import json
import os
import subprocess
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
import sys
sys.path.insert(0, HERE)
import locales  # noqa: E402
import derive_access_cost as dac  # noqa: E402


def _head_sha():
    try:
        return subprocess.check_output(["git", "-C", ROOT, "rev-parse", "--short", "HEAD"],
                                       text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return "(unknown)"


def _fiche_facts():
    status = Counter()
    access = Counter()
    for fp in glob.glob(os.path.join(ROOT, "Json", "*.json")):
        d = json.load(open(fp, encoding="utf-8"))
        st = d.get("status") or "published"
        status[st] += 1
        if st not in ("draft", "unverified"):
            access[dac.derive(d)[0]] += 1
    return status, access


def _count_html():
    n = 0
    for _dp, _dn, files in os.walk(ROOT):
        if "/_site" in _dp or "/node_modules" in _dp or "/.git" in _dp:
            continue
        n += sum(1 for f in files if f.endswith(".html"))
    return n


def _sitemap_urls():
    p = os.path.join(ROOT, "sitemap.xml")
    if not os.path.exists(p):
        return 0
    return open(p, encoding="utf-8").read().count("<loc>")


def _registry_count(rel, key="lieux"):
    p = os.path.join(ROOT, rel)
    if not os.path.exists(p):
        return None
    try:
        d = json.load(open(p, encoding="utf-8"))
    except Exception:
        return None
    for k in (key, "facets", "pages", "hubs"):
        v = d.get(k) if isinstance(d, dict) else None
        if isinstance(v, (list, dict)):
            return len(v)
    return len(d) if isinstance(d, (list, dict)) else None


def _gates():
    return sorted(os.path.basename(p) for p in glob.glob(os.path.join(HERE, "gate_*.py")))


def main():
    status, access = _fiche_facts()
    published = sum(v for k, v in status.items() if k not in ("draft", "unverified"))
    gates = _gates()
    lines = []
    A = lines.append

    A("# PROJECT-STATE — Loisirs74.fr")
    A("")
    A("> GENERATED by `scripts/build_project_state.py` (build_all step) from the live repo —")
    A("> **do not hand-edit.** Every number is derived from `data/languages.json`, `Json/*.json`,")
    A("> the built tree and `scripts/gate_*.py`, so it cannot drift. For the *how it's built*")
    A("> see `ARCHITECTURE.md`; for *what's next* see the open consolidation JOBs.")
    A("> (No commit sha is embedded — that would churn every commit; `git log` carries it.)")
    A("")
    A("## Locale roster (derived from data/languages.json)")
    A("")
    A("| roster | langs |")
    A("|---|---|")
    for name in ("VISIBLE", "PROSE", "PROSE_SECONDARY", "FACTS_PUBLISHED",
                 "STAGED_INDEXABLE", "STAGED", "HELD"):
        val = getattr(locales, name, ())
        A(f"| `{name}` | {', '.join(val) if val else '(empty)'} |")
    A("")
    A("## Content")
    A("")
    A("| metric | value |")
    A("|---|---|")
    A(f"| fiche JSONs (total) | **{sum(status.values())}** |")
    A(f"| published | **{published}** |")
    for k in ("draft", "unverified"):
        if status.get(k):
            A(f"| {k} | {status[k]} |")
    A(f"| access-cost: free / free_seasonal / paid | {access['free']} / {access['free_seasonal']} / {access['paid']} |")
    A(f"| built HTML pages | {_count_html()} |")
    A(f"| sitemap URLs | {_sitemap_urls()} |")
    fh = _registry_count("data/facet-hubs.json", "facets")
    ih = _registry_count("data/intent-registry.json", "pages")
    if fh is not None:
        A(f"| facet hubs (data/facet-hubs.json) | {fh} |")
    if ih is not None:
        A(f"| intent pages (data/intent-registry.json) | {ih} |")
    A("")
    A(f"## CI gates ({len(gates)})")
    A("")
    A("Every push to `main` runs `build_all` behind the build gate. Standalone gate scripts:")
    A("")
    for g in gates:
        A(f"- `{g}`")
    A("")
    A("---")
    A("*© 2026 · Bleu canard édition · generated, never authored · 🦆*")

    out = os.path.join(ROOT, "PROJECT-STATE.md")
    open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"wrote {out}: {published} published lieux, {len(gates)} gates, HEAD {_head_sha()}")


if __name__ == "__main__":
    main()
