#!/usr/bin/env python3
"""build_security_txt.py — emit .well-known/security.txt (RFC 9116).

WHY IT IS GENERATED AND NEVER HAND-TYPED
  RFC 9116 requires an `Expires` field, ISO-8601, at most one year out. A
  lapsed `Expires` makes the file INVALID — linters and security scanners flag
  the domain. A hardcoded date is therefore a guaranteed future defect: it is
  correct on the day it is written and wrong forever after.

  So the date is computed at build time (today + 364 days; 364 rather than 365
  keeps a day of margin under the RFC's ceiling). Every push refreshes it, so
  it regenerates far faster than its own validity window and can never lapse.
  This is the consolidation law: nothing the build can derive is hand-maintained.

DETERMINISM — why the timestamp is floored to midnight UTC
  The obvious formula, `now + 364 days`, carries the current time of day, so two
  builds a minute apart emit different bytes and the build's byte-identical
  idempotency check fails. Flooring `now` to 00:00:00Z first makes the output
  stable for the whole UTC day while still refreshing daily. The file
  legitimately changes once per day — that is the point of it, not drift.

Usage:
    python3 scripts/build_security_txt.py          # write the file
"""
from datetime import datetime, timedelta, timezone
import siteconfig  # HANDOFF-73: per-site identity
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / ".well-known" / "security.txt"

VALID_DAYS = 364  # one day of margin under the RFC 9116 one-year ceiling


def render(now=None):
    """RFC 9116 body. Field order follows the RFC's own examples."""
    now = now or datetime.now(timezone.utc)
    # floor to midnight UTC so the output is byte-stable within a day
    day = now.replace(hour=0, minute=0, second=0, microsecond=0)
    expires = (day + timedelta(days=VALID_DAYS)).strftime("%Y-%m-%dT%H:%M:%S.000Z")
    return (
        f"Contact: mailto:{siteconfig.CONTACT_EMAIL}\n"
        f"Expires: {expires}\n"
        "Preferred-Languages: fr, en\n"
        f"Canonical: {siteconfig.BASE_URL}/.well-known/security.txt\n"
        f"# {siteconfig.SITE_NAME} — bleu-canard éditions\n"
        "# Generated by scripts/build_security_txt.py — do not hand-edit;\n"
        "# Expires is recomputed on every build so it cannot lapse.\n"
    )


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = render()
    OUT.write_text(body, encoding="utf-8")
    expires = [l for l in body.splitlines() if l.startswith("Expires:")][0]
    print(f"build_security_txt: wrote {OUT.relative_to(ROOT)} · {expires}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
