#!/usr/bin/env python3
"""Protected-placements byte-guard — HANDOFF-39A-B (permanent).

The two partner placements (cheznousalaplage.com · chaletdutornet.com) are
paid, contractual, and byte-frozen. The existing placement/card-diff gates
prove the CARD survives; this gate freezes the WHOLE CARRYING PAGE:

  1. grep the built tree for either partner domain → the carrying-page list
  2. sha256 every carrying page
  3. compare list + hashes against the committed manifest
     reports/protected-placements.md

ANY change — a page gained, lost, or a single byte moved — is red, UNLESS an
`EDMASTER-APPROVED: <pages|all>` trailer appears in the last 20 reachable
commit messages (PR merge refs carry synthetic messages, so the history walk
is what finds the feature commit's trailer). Known, intended friction: even a
site-wide CSS tweak (the stylesheet is inlined per page) needs the trailer —
that IS the triple-check rule, encoded.

Modes:
    python3 scripts/gate_protected_placements.py                  # gate (CI)
    python3 scripts/gate_protected_placements.py --write-manifest # regenerate
        (only alongside an EDMASTER-APPROVED commit; the diff shows the scope)
"""
import argparse
import hashlib
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "reports", "protected-placements.md")
DOMAINS = ("cheznousalaplage.com", "chaletdutornet.com")
TRAILER_RE = re.compile(r"^EDMASTER-APPROVED:\s*(.+)$", re.M)
# derived / non-page trees never scanned: the publish copy, snapshots, tooling
SKIP_DIRS = {"_site", ".git", "node_modules", "reports", "translations",
             "incoming-generics", "__pycache__", ".axis"}


def carrying_pages(tree):
    """{relpath: sha256} for every .html under `tree` that names a partner."""
    out = {}
    for dirpath, dirnames, filenames in os.walk(tree):
        dirnames[:] = [d for d in dirnames
                       if d not in SKIP_DIRS and not d.startswith(".")]
        for fn in filenames:
            if not fn.endswith(".html"):
                continue
            p = os.path.join(dirpath, fn)
            raw = open(p, "rb").read()
            if any(d.encode() in raw for d in DOMAINS):
                rel = os.path.relpath(p, tree).replace(os.sep, "/")
                out[rel] = hashlib.sha256(raw).hexdigest()
    return out


def render_manifest(pages):
    lines = [
        "# Protected placements — byte manifest (HANDOFF-39A-B)",
        "",
        "GENERATED by `scripts/gate_protected_placements.py --write-manifest`.",
        "Every built page that carries a partner domain "
        f"({' · '.join(DOMAINS)}), with its sha256. The build-gate compares the",
        "live tree against this table on EVERY run; any drift is red unless the",
        "commit history carries an `EDMASTER-APPROVED: <pages|all>` trailer.",
        "",
        f"Pages: {len(pages)}",
        "",
        "| page | sha256 |",
        "|---|---|",
    ]
    for rel in sorted(pages):
        lines.append(f"| {rel} | {pages[rel]} |")
    return "\n".join(lines) + "\n"


def parse_manifest(path):
    if not os.path.exists(path):
        return None
    pages = {}
    for line in open(path, encoding="utf-8"):
        m = re.match(r"^\|\s*(\S+)\s*\|\s*([0-9a-f]{64})\s*\|\s*$", line)
        if m:
            pages[m.group(1)] = m.group(2)
    return pages


def approval_trailer(tree, depth=20):
    """The EDMASTER-APPROVED trailer from the last `depth` reachable commits,
    or None. A non-repo tree (the mutation test's temp dir) yields None."""
    try:
        out = subprocess.run(["git", "-C", tree, "log", f"-{depth}", "--format=%B"],
                             capture_output=True, text=True, timeout=30)
        if out.returncode != 0:
            return None
        m = TRAILER_RE.search(out.stdout)
        return m.group(1).strip() if m else None
    except Exception:
        return None


def main():
    ap = argparse.ArgumentParser(description="Byte-freeze the partner carrying pages.")
    ap.add_argument("--tree", default=ROOT)
    ap.add_argument("--manifest", default=MANIFEST)
    ap.add_argument("--write-manifest", action="store_true",
                    help="Regenerate the manifest from the current tree.")
    args = ap.parse_args()

    current = carrying_pages(args.tree)
    if not current:
        print("::error::0 carrying pages found — the placements themselves are gone?",
              file=sys.stderr)
        sys.exit(1)

    if args.write_manifest:
        os.makedirs(os.path.dirname(args.manifest), exist_ok=True)
        with open(args.manifest, "w", encoding="utf-8") as fh:
            fh.write(render_manifest(current))
        print(f"manifest written: {args.manifest} ({len(current)} carrying pages)")
        return

    baseline = parse_manifest(args.manifest)
    if baseline is None:
        print(f"::error::manifest missing: {args.manifest} — run --write-manifest "
              "in an EDMASTER-APPROVED commit", file=sys.stderr)
        sys.exit(1)

    added = sorted(set(current) - set(baseline))
    removed = sorted(set(baseline) - set(current))
    changed = sorted(p for p in set(current) & set(baseline)
                     if current[p] != baseline[p])

    print(f"gate_protected_placements: {len(current)} carrying pages vs "
          f"manifest {len(baseline)}")
    if not (added or removed or changed):
        print("✓ protected placements byte-identical to the manifest")
        sys.exit(0)

    trailer = approval_trailer(args.tree)
    print(f"::warning::placement drift: +{len(added)} −{len(removed)} "
          f"~{len(changed)} page(s)")
    for label, items in (("ADDED", added), ("REMOVED", removed), ("CHANGED", changed)):
        for p in items[:10]:
            print(f"    {label}: {p}")
        if len(items) > 10:
            print(f"    {label}: … and {len(items) - 10} more")
    if trailer:
        print(f"✓ EDMASTER-APPROVED trailer found in recent history: {trailer!r}")
        print("  drift is APPROVED — remember to refresh the manifest "
              "(--write-manifest) in the same change")
        sys.exit(0)
    print("::error::protected carrying pages drifted WITHOUT an "
          "EDMASTER-APPROVED trailer in the last 20 commits. Either revert the "
          "drift, or get Edmaster's sign-off and commit with the trailer + a "
          "refreshed manifest.")
    sys.exit(1)


if __name__ == "__main__":
    main()
